.PHONY: test native-test
test:
	go test ./...
	cd apps/marker && go test ./...
	cd apps/waf && go test ./...
	cd apps/marker/envoy && go test ./...
	cd apps/waf/envoy && go test ./...
	cd hosts/envoy && go test ./...
native-test:
	go test ./...
	cd apps/marker && go test ./...
	cd apps/waf && go test ./...
	cd apps/marker/envoy && go test ./...
	cd apps/waf/envoy && go test ./...
	$(MAKE) -C hosts/envoy native-test
