.PHONY: test native-test
test:
	go test ./...
	cd apps/marker && go test ./...
	cd apps/waf && go test ./...
	cd hosts/envoy/handoff && go test ./...
	cd apps/marker/envoy && go test ./...
	cd apps/waf/envoy && go test ./...
	cd hosts/envoy && go test ./...
native-test:
	go test ./...
	cd apps/marker && go test ./...
	cd apps/waf && go test ./...
	cd hosts/envoy/handoff && go test ./...
	cd apps/marker/envoy && go test ./...
	cd apps/waf/envoy && go test ./...
	$(MAKE) -C hosts/envoy native-test

.PHONY: demo-build
demo-build:
	$(MAKE) -C hosts/envoy native-build
	mkdir -p bin
	cp hosts/envoy/.bin/fig bin/fig
	cp hosts/envoy/.bin/libfig_match.so bin/libfig_match.so
