services:
  proxy:
    build:
      context: ../..
      dockerfile: spike/envoy/Dockerfile
      target: proxy
    ports:
      - "127.0.0.1::10000"
      - "127.0.0.1::9901"
    depends_on:
      - echo
  echo:
    build:
      context: ../..
      dockerfile: spike/envoy/Dockerfile
      target: echo
    ports:
      - "127.0.0.1::8080"
